### ISSUE TITLE
Cover Art not showing for at least a month

### ISSUE THREAD

**Issue by babawich** [DSilence/MiniPie#50]
Using 1.0.2.237 and windows 7.. cover art has not been showing for a little while now.  Just shows a monitor with a question mark. The player itself works great as usual.

**Comment by DSilence** [comment]
Just released an update today with a possible fix. If it doesn't help, try logging our and back in using settings.

**Comment by babawich** [comment]
I never had signed in before so don't think that is the problem. Still does not work here. I tried signing in but it does not show I did after allowing in Spotify. Using Windows 7 here if that helps

**Comment by DSilence** [comment]
Can I ask you to send me the log file? It's located in c:\Users\{Your User name}\AppData\Roaming\MiniPie\MiniPie.log
Thanks!

**Comment by babawich** [comment]
Here they are:
2017-09-03 09:23:18.1793|WARN|MiniPie.Core.ProductionLogger|Failed to
process Spotify request:
https://api.spotify.com/v1/tracks/0MAIxtXWimwhAAQOST9jp7; the error
is:Response status code does not indicate success: 401 (Unauthorized).
2017-09-03 09:23:18.2743|WARN|MiniPie.Core.ProductionLogger|Failed to
retrieve cover from Spotify
2017-09-03 09:23:21.1745|WARN|MiniPie.Core.ProductionLogger|Failed to
process Spotify request:
https://api.spotify.com/v1/tracks/0yyRL7Rxr4oJ6uI7DYe2OT; the error
is:Response status code does not indicate success: 401 (Unauthorized).
2017-09-03 09:23:21.1795|WARN|MiniPie.Core.ProductionLogger|Failed to
retrieve cover from Spotify
2017-09-03 09:23:47.1949|WARN|MiniPie.Core.ProductionLogger|Failed to
process Spotify request:https://api.spotify.com/v1/me; the error
is:Response status code does not indicate success: 401 (Unauthorized).
2017-09-03 09:23:47.2349|WARN|MiniPie.Core.ProductionLogger|User login
failed
2017-09-03 09:24:14.2425|WARN|MiniPie.Core.ProductionLogger|Failed to
process Spotify request:
https://api.spotify.com/v1/tracks/2GlAH40dBbcSUEtK9uyFu0; the error
is:Response status code does not indicate success: 401 (Unauthorized).
2017-09-03 09:24:14.2485|WARN|MiniPie.Core.ProductionLogger|Failed to
retrieve cover from Spotify
2017-09-03 10:14:01.3393|WARN|MiniPie.Core.ProductionLogger|Failed to
process Spotify request:
https://api.spotify.com/v1/tracks/3fkfiYZdDNi6PAWFaTxlGn; the error
is:Response status code does not indicate success: 401 (Unauthorized).
2017-09-03 10:14:01.3393|WARN|MiniPie.Core.ProductionLogger|Failed to
retrieve cover from Spotify


Thanks.

**Comment by DSilence** [comment]
A couple of month ago spotify changed their API so that only authorized user can access track information. Looks like in your case the authorization callback isn't called correctly. This might be the case of application installation being corrupted. Could you try a clean install (uninstalling and installing using setup.exe) and logging in?

**Comment by babawich** [comment]
It looks like I got it working! I just ran an old setup again as the newer
setup was being deleted on download by Norton due to low users. Will let
you know if anything changes.. thanks man!

**Comment by DSilence** [comment]
No problem, glad that this was resolved!
